### ISSUE TITLE
Afficher un message "chercher dans le catalogue" si pas dans les simulcasts

### ISSUE THREAD

**Issue by yattoz** [yattoz/SimulcastFR-website#3]
(Sur suggestion d'AxelTerizaki)

Il faudrait que, si on fait une recherche et qu'elle ne retourne aucun résultat, le site affiche un message du type : 
"Aucun résultat pour la recherche !
Si vous cherchez une oeuvre dont la diffusion est terminée, recherchez plutôt dans le catalogue.", avec [rechercher dans le catalogue] un lien cliquable qui bascule en vue catalogue. (le filtre reste actif, rien à faire de plus de ce côté là)

**Comment by AxelTerizaki** [comment]
En fait pour être plus précis il faudrait que quand tu tapes un truc ça sépare les résultats en deux : simulcasts puis catalogue, comme ça les gens savent si une série est en simulcast ou non directement, en plus de voir chez qui elle est

**Comment by yattoz** [comment]
Honnêtement, flemme ultime. >_<
J'ai fait un lien vers le catalogue qui apparait si la recherche est vide. Là j'ai fait ça en 3 minutes, c'est un bon rapport temps passé / solution obtenue, et c'est en ligne (c'est basique mais relativement clair et efficace). Si tu veux proposer mieux, je t'en prie, fork, PR, tout ça !
Voir commit https://github.com/yattoz/SimulcastFR-website/commit/a1618f62f6d18d645cd4a44815fb8065ccac71d0
